### ISSUE TITLE
Themes not working in Mozilla Firefox 35.0.1 for Ubuntu 14.04

### ISSUE THREAD

**Issue by idrisjafer** [PolymerThemes/polymer-themes#2]
When I include any theme in my project, none of the paper elements are being styled in Mozilla Firefox. In other browsers like chrome,it is working fine but not in Mozilla. When I see the console I find the following error:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by PolymerThemes** [comment]
Thank you for creating this issue @idrisjafer and apologies for the delayed response.

Can you please try adding `shim-shadowdom` to the CSS link element that references the theme CSS file, e.g.:

```<link rel="stylesheet" type="text/css" href="theme.css" shim-shadowdom>```

The reason for this is explained here: https://www.polymer-project.org/docs/polymer/styling.html#sdcss

We have updated the documentation on [polymerthemes.com](https://polymerthemes.com/help/) to reflect this.
