### ISSUE TITLE
Implementing html files with Polymer

### ISSUE THREAD

**Issue by ghost** [PolymerThemes/polymer-themes#4]
As a newbie to Polymer...

What's the best way to implement the html files? I've tried various strategies (with little success) and the farthest I've gotten is a solid color of the html file. 

How would I add the formatting and styling of the html files to the Polymer framework? 

Thanks!

**Comment by PolymerThemes** [comment]
Hello Mon Baroi, and thank you for your message!

Using our themes is very easy: simply import the theme html file into your index page, as described on our [Getting Started](https://polymerthemes.com/help/) page.

Besides using our themes directly, you can create your own custom styles by wrapping your CSS inside a style tag with the attribute `is="custom-style"`.

For more information, have a look at the [Polymer Project documentation](https://www.polymer-project.org/1.0/docs/start/getting-the-code.html).
