### ISSUE TITLE
Secondary Button Color also changes Primary Button Color to Same Color

### ISSUE THREAD

**Issue by dman777** [PolymerThemes/polymer-themes#5]
Question, please...

This is with `Change all matching colors when I make a change` enabled,

When the page first loads, the primary button and  secondary button are different  colors. But if I change the secondary button then the primary button also changes to the same color. 

Is this a bug? If not, what rule/logic in Material Design is it where the secondary button color should also be the primary button color?

**Comment by dman777** [comment]
###### Update:

This is more of the fault of the gui app. The fix is to choose primary color, click preview, then change the secondary color.

**Comment by PolymerThemes** [comment]
Hello dman777! Unfortunately, we have not been able to reproduce this issue. If it continues to occur on your end, could you please provide additional information so that we can investigate further; such as the browser and version that you are using. Thanks!

**Comment by PolymerThemes** [comment]
Assuming fixed due to lack of feedback. If you are still experiencing this issue please feel free to open up a new issue.
