### ISSUE TITLE
There is no download button if you just want the base version

### ISSUE THREAD

**Issue by gertcuykens** [PolymerThemes/polymer-themes#9]
example https://polymerthemes.com/custom-style/?base=dark-side

![image](https://cloud.githubusercontent.com/assets/863731/10741944/c21a4546-7c2a-11e5-98b5-e7a3d6d9961e.png)

I know on the home page there is but there should be also on the custom-style page if you don't make changes.

**Comment by PolymerThemes** [comment]
Great suggestion, this should make it into the next release!
